"use client";
import { Box } from "@mui/material";

import { breadcrumb__children, breadcrumb__main, layoutdefault__box } from "./styles";

import { Header, MenuWrapper } from "@/components";
import type { Metadata } from "next";
import { SessionProvider } from "next-auth/react";

interface LayoutDefaultProps {
  children: React.ReactNode;
  session?: any;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export const LayoutDefault = ({ children, session }: LayoutDefaultProps) => {
  return (
    <SessionProvider session={session}>
      <Box sx={layoutdefault__box}>
        <MenuWrapper />
        <Box component="main" sx={breadcrumb__main}>
          <Header />
          <Box component="main" sx={breadcrumb__children}>
            {children}
          </Box>
        </Box>
      </Box>
    </SessionProvider>
  );
};
