import "./globals.css";

import { CssBaseline, ThemeProvider } from "@mui/material";
import type { Metadata } from "next";

import theme from "@/styles/theme/theme";
export const metadata: Metadata = {
  title: "Credit Score",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
