export const TABLECONTRACTS = [
  {
    id: 1,
    name: "Ana",
    nif: "123456789",
    reestruturadoPorDificuldadesFinanceiras: false,
    reestruturadoSemDificuldadesFinanceiras: false,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: false,
    quebraDeContrato: true,
    emNegociacao: false,
    reestruturado: false,
    pari: false,
    persi: false,
    per: false,
    tribunal: false
  },
  {
    id: 2,
    name: "Carlos",
    nif: "987654321",
    reestruturadoPorDificuldadesFinanceiras: false,
    reestruturadoSemDificuldadesFinanceiras: false,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: false,
    quebraDeContrato: false,
    emNegociacao: true,
    reestruturado: false,
    pari: false,
    persi: false,
    per: false,
    tribunal: false
  },
  {
    id: 3,
    name: "João",
    nif: "111222333",
    reestruturadoPorDificuldadesFinanceiras: false,
    reestruturadoSemDificuldadesFinanceiras: false,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: false,
    quebraDeContrato: false,
    emNegociacao: false,
    reestruturado: false,
    pari: false,
    persi: false,
    per: false,
    tribunal: false
  },
  {
    id: 4,
    name: "Maria",
    nif: "222333444",
    reestruturadoPorDificuldadesFinanceiras: true,
    reestruturadoSemDificuldadesFinanceiras: false,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: false,
    quebraDeContrato: false,
    emNegociacao: false,
    reestruturado: false,
    pari: false,
    persi: false,
    per: false,
    tribunal: false
  },
  {
    id: 5,
    name: "Pedro",
    nif: "333444555",
    reestruturadoPorDificuldadesFinanceiras: false,
    reestruturadoSemDificuldadesFinanceiras: true,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: false,
    quebraDeContrato: false,
    emNegociacao: false,
    reestruturado: false,
    pari: false,
    persi: false,
    per: false,
    tribunal: false
  },
  {
    id: 6,
    name: "Luís",
    nif: "444555666",
    reestruturadoPorDificuldadesFinanceiras: false,
    reestruturadoSemDificuldadesFinanceiras: false,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: false,
    quebraDeContrato: false,
    emNegociacao: false,
    reestruturado: false,
    pari: false,
    persi: false,
    per: false,
    tribunal: true
  },
  {
    id: 7,
    name: "Cláudia",
    nif: "555666777",
    reestruturadoPorDificuldadesFinanceiras: false,
    reestruturadoSemDificuldadesFinanceiras: false,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: true,
    quebraDeContrato: false,
    emNegociacao: false,
    reestruturado: false,
    pari: false,
    persi: false,
    per: false,
    tribunal: false
  },
  {
    id: 8,
    name: "Fábio",
    nif: "666777888",
    reestruturadoPorDificuldadesFinanceiras: false,
    reestruturadoSemDificuldadesFinanceiras: false,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: false,
    quebraDeContrato: false,
    emNegociacao: false,
    reestruturado: false,
    pari: false,
    persi: true,
    per: false,
    tribunal: false
  },
  {
    id: 9,
    name: "Sofia",
    nif: "777888999",
    reestruturadoPorDificuldadesFinanceiras: false,
    reestruturadoSemDificuldadesFinanceiras: false,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: false,
    quebraDeContrato: false,
    emNegociacao: false,
    reestruturado: false,
    pari: false,
    persi: false,
    per: true,
    tribunal: false
  },
  {
    id: 10,
    name: "Ricardo",
    nif: "888999000",
    reestruturadoPorDificuldadesFinanceiras: false,
    reestruturadoSemDificuldadesFinanceiras: false,
    defaultTecnico: false,
    writeOff: false,
    chargeOff: false,
    quebraDeContrato: false,
    emNegociacao: false,
    reestruturado: false,
    pari: false,
    persi: false,
    per: false,
    tribunal: false
  }
];
